### ISSUE TITLE
Looks like http://raynicholus.com/feed.xml is empty

### ISSUE THREAD

**Issue by sgtpep** [rnicholus/raynicholus.com#1]

**Comment by rnicholus** [comment]
Thanks for the report. I'll look into this over the weekend.

**Comment by rnicholus** [comment]
Completed in e7c9a3badeb21869a271afcac276d1767dd329a1. This site only references external posts at the moment, and feed.xml wasn't setup to handle these. It is now though. Let me know if you see any other issues.
